command:                  # If there are more than one command, it will be executed in sequentially
  - '[CONSOLE] weather rain'         # place the command that you want to execute in ''
  - '[PLAYER] help'
  - '[PLAYER] plugins'
  - '[CONSOLE] time set day'
  - '[OP] say The players in the server: %playerlist_all,normal,yes,list%'
  - '[OP] say The food level of %player_name% is %player_food_level%'
  - '[CONSOLE] deop %player_name%'
  - '[CONSOLE] op %player_name%'

action: SHIFT                     # place the key that you feel comfortable to use this Plugin. (SHIFT, F, SHIFT+F)