commands:
  - 'weather rain'         # place the command that you want to execute in ''
  - 'seed'
  - 'weather clear'
  - 'time set night'

executor:
  - 'CONSOLE'

action:                     # place the key that you feel comfortable to use this Plugin.
  - 'SHIFT'