commands:                  # If there are more than one command, it will be executed in sequentially
  - '[CONSOLE] weather rain'         # place the command that you want to execute in ''
  - '[PLAYER] seed'
  - '[PLAYER] weather clear'
  - '[CONSOLE] time set day'

action: SHIFT                     # place the key that you feel comfortable to use this Plugin. (SHIFT, F, SHIFT+F)
